# Generated by Django 2.2 on 2019-04-17 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0002_auto_20190417_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_stuff',
        ),
    ]
