# Generated by Django 2.2 on 2019-04-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0003_remove_userprofile_is_stuff'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_stuff',
            field=models.BooleanField(default=False),
        ),
    ]
